name: app
description: "GIM test app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  get_it: ^7.7.0
  sqflite: 2.3.3
  location: ^7.0.0
  injectable: ^2.4.2
  go_router: ^14.2.1
  geolocator: ^12.0.0
  google_fonts: ^6.2.1
  flutter_bloc: ^8.1.6
  path_provider: ^2.1.3
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.6
  json_annotation: ^4.9.0
  bloc_concurrency: ^0.2.5
  freezed_annotation: ^2.4.3
  shared_preferences: ^2.2.3
  permission_handler: ^11.3.1
  google_maps_flutter: ^2.7.0

  #  firebase
  firebase_core: ^3.2.0
  firebase_analytics: ^11.2.0
  firebase_crashlytics: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed:
  build_runner:
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - dev.env
    - prod.env